app_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }
contact:
    path: /contact/
    defaults: { _controller: AppBundle:Default:contact }
about:
    path: /about/
    defaults: { _controller: AppBundle:Default:about }
post:
    path: /post/
    defaults: { _controller: AppBundle:Default:post }
add:
    path: /add/{name}/{phone}
    defaults: { _controller: AppBundle:Default:add }
formAnnu:
    path: /annuaire/
    defaults: { _controller: AppBundle:Default:annuaire }
searchAnnu:
    path: /search/{name}/{phone}
    defaults: { _controller: AppBundle:Default:search }